### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by gutenye** [canghailan/weapp-global#1]
看了package.json里面的描述，还是没懂。

**Comment by canghailan** [comment]
非常抱歉，这是我的作为测试用的包，所以发布的时候没有描述清楚。


微信小程序不能直接使用部分npm包，如lodash，因为初始化时缺少一些全局变量，导致require失败。
weapp-global导出了这些缺少的全局变量，import-loader中指定global参数后即可正常require。


代码并没有经过测试，请仅作为一个思路。


原始邮件
发件人:Guten Yenotifications@github.com
收件人:canghailan/weapp-globalweapp-global@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年2月11日(周六) 20:14
主题:[canghailan/weapp-global] 请问如何使用？ (#1)


看了package.json里面的描述，还是没懂。

**Comment by gutenye** [comment]
多谢，成功导入lodash~~
